version: "3.7"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src/templates:/app/templates
      - ./src/assets:/app/assets
      - ./src/app:/app/app
    command: >
      sh -c "./docker-entrypoint.sh &&
      python manage.py runserver 0.0.0.0:8000"
    environment:
      - DOCKER_COMPOSE=1
      # - DEBUG=0
      # - DB_HOST=db
      # - DB_NAME=app
      # - DB_USER=postgres-user
      # - DB_PASS=supersecretpassword
  #   depends_on:
  #     - db

  # db:
  #   image: postgres:10-alpine
  #   environment:
  #     - POSTGRES_DB=app
  #     - POSTGRES_USER=postgres-user
  #     - POSTGRES_PASSWORD=supersecretpassword
